{
 "title": "Prometheus: Apache",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "apache",
    "label": "Apache",
    "query": "label_values(apache_scoreboard_current,exporter_name)"
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(apache_balancer_requests_total{exporter_name=\"$apache\"},cluster)"
   },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(apache_endpoint_response_time_seconds_count{exporter_name=\"$apache\"}, method)"
   },
   { "name": "percentile", "label": "percentile", "query": "50, 75, 95, 99" }
  ]
 },
 "panels": [
  {
   "title": "Requests Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(apache_accesses_total{exporter_name=\"$apache\"}) by (exporter_name)"
    }
   ]
  },
  {
   "title": "IO Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(apache_traffic_bytes_total{exporter_name=\"$apache\"}) by (exporter_name)"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(apache_requests_per_second{exporter_name=\"$apache\"}) by (exporter_name)"
    }
   ]
  },
  {
   "title": "Bytes Per Second",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(apache_io_bytes_per_second{exporter_name=\"$apache\"}) by (exporter_name)"
    }
   ]
  },
  {
   "title": "Bytes Per Request",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(apache_io_bytes_per_request{exporter_name=\"$apache\"}) by (exporter_name)"
    }
   ]
  },
  {
   "title": "Nodes in UNKNOW status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(apache_balancer_route_unknown{exporter_name=\"$apache\"})"
    }
   ]
  },
  {
   "title": "Nodes OK",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_balancer_route_ok{exporter_name=\"$apache\", cluster=\"$cluster\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Nodes DISABLED",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_balancer_route_disabled{exporter_name=\"$apache\", cluster=\"$cluster\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Nodes FAILED",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_balancer_route_error{exporter_name=\"$apache\", cluster=\"$cluster\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests Served By Node, 1h",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(apache_balancer_requests_total{exporter_name=\"$apache\", cluster=\"$cluster\"}[1h])) by (host, route)",
     "legendFormat": "{{host}} / {{route}}"
    }
   ]
  },
  {
   "title": "Workers By Status",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apache_scoreboard_current{exporter_name=\"$apache\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests, 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apache_balancer_requests_total{exporter_name=\"$apache\", cluster=\"$cluster\"}[1m])) by (host, route)",
     "legendFormat": "{{host}} / {{route}}"
    }
   ]
  },
  {
   "title": "Requests Served By Node %, 5m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(apache_balancer_requests_total{exporter_name=\"$apache\", cluster=\"$cluster\"}[5m])) by (host, route)",
     "legendFormat": "{{host}} / {{route}}"
    }
   ]
  },
  {
   "title": "IO Bytes,  30m Average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(increase(apache_balancer_read_bytes_total{exporter_name=\"$apache\", cluster=\"$cluster\"}[30m])) by (host, route)",
     "legendFormat": "RD: {{host}} / {{route}}"
    },
    {
     "expr": "avg(increase(apache_balancer_write_bytes_total{exporter_name=\"$apache\", cluster=\"$cluster\"}[30m])) by (host, route)",
     "legendFormat": "WR: {{host}} / {{route}}"
    }
   ]
  },
  {
   "title": "Response Time By Endpoints. $percentile Percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.$percentile, sum(increase(apache_endpoint_response_time_seconds_bucket{exporter_name=\"$apache\", method=~\"$method\"}[1m])) by (exported_endpoint,le)) > 0",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Requests By Endpoints, 1m",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(increase(apache_endpoint_response_time_seconds_count{exporter_name=\"$apache\", method=~\"$method\"}[1m])) by (method, exported_endpoint) > 0)",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  }
 ]
}